# Generated by Django 5.2 on 2025-06-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('shift', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino')], max_length=1, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Bibliotecario',
                'verbose_name_plural': 'Bibliotecarios',
                'ordering': ['id'],
            },
        ),
    ]
