# Generated by Django 5.2 on 2025-06-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotecarios', '0001_initial'),
        ('clientes', '0001_initial'),
        ('livros', '0002_remove_livro_category_livrocategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data de inicio')),
                ('end_date', models.DateField(verbose_name='Prazo de entrega')),
                ('status', models.CharField(blank=True, choices=[('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Em andamento', max_length=20, null=True, verbose_name='Status')),
                ('bibliotecario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecarios.bibliotecario')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimos.emprestimo')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro')),
            ],
            options={
                'verbose_name': 'Item de emprestimo',
                'verbose_name_plural': 'Itens de emprestimo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='item_emprestimo',
            field=models.ManyToManyField(blank=True, through='emprestimos.ItemEmprestimo', to='livros.livro'),
        ),
    ]
