# Generated by Django 5.2 on 2025-06-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='client',
            new_name='cliente',
        ),
    ]
