# Generated by Django 5.2 on 2025-06-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_rename_client_emprestimo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='bibliotecario',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='start_date',
        ),
    ]
