# Generated by Django 5.2 on 2025-06-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='photo',
            field=models.ImageField(default='autor_photos/default_author.jpg', upload_to='autor_photos/', verbose_name='Foto'),
        ),
    ]
