# Generated by Django 5.2 on 2025-06-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '__first__'),
        ('categorias', '__first__'),
        ('editoras', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('release_date', models.DateField(verbose_name='Data Publicacao')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores.autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editoras.editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['id'],
            },
        ),
    ]
