# Generated by Django 5.2 on 2025-06-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '__first__'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='category',
        ),
        migrations.CreateModel(
            name='LivroCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro')),
            ],
            options={
                'verbose_name': 'Item de categoria',
                'verbose_name_plural': 'Itens de categorias',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='livro_category',
            field=models.ManyToManyField(blank=True, through='livros.LivroCategoria', to='categorias.categoria'),
        ),
    ]
